version: '3.7'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    ports:
      - "27017"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
      - "15672"
    networks:
      - backend

  server:
    image: server
    build:
      context: ./
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080"
    networks:
      - backend
    # volumes:
    #   - ./:/app
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  db-data:

networks:
  backend:
    external: true